/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../components/AppFooter.vue')['default']
    AppHeader: typeof import('./../components/AppHeader.vue')['default']
    DisplayError: typeof import('./../components/state/DisplayError.vue')['default']
    LoadingSpinner: typeof import('./../components/state/LoadingSpinner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterLinkUp: typeof import('./../components/RouterLinkUp.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    TailwindEmptyState: typeof import('./../components/state/tailwind-empty-state.vue')['default']
    TestComponent: typeof import('./../components/TestComponent.vue')['default']
    ThemeSwitch: typeof import('./../components/ThemeSwitch.vue')['default']
    UApp: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_a31afabae1f7364e9a87ab4722eec2bf/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_a31afabae1f7364e9a87ab4722eec2bf/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_a31afabae1f7364e9a87ab4722eec2bf/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UForm: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_a31afabae1f7364e9a87ab4722eec2bf/node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_a31afabae1f7364e9a87ab4722eec2bf/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UInput: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_a31afabae1f7364e9a87ab4722eec2bf/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    USwitch: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+exte_a31afabae1f7364e9a87ab4722eec2bf/node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
  }
}
